apiVersion: v1
kind: ServiceAccount
metadata:
  name: cloud-backend
  namespace: hybrid-demo-cloud
  annotations:
    azure.workload.identity/client-id: "REPLACE_WITH_MANAGED_IDENTITY_CLIENT_ID"
    azure.workload.identity/tenant-id: "REPLACE_WITH_ENTRA_TENANT_ID"
  labels:
    azure.workload.identity/use: "true"
