apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: hybrid-demo-cloud
resources:
- backend.yaml

images:
- name: ghcr.io/hybrid-multi-agents/backend
  newName: ghcr.io/jetzlstorfer/hybrid-multi-agents/backend
  newTag: sha-10bd8d0967a2cc1f9a0ce950eb30cc831c4916c6
- name: ghcr.io/jetzlstorfer/hybrid-multi-agents/backend
  newName: ghcr.io/jetzlstorfer/hybrid-multi-agents/backend
  newTag: sha-ffd816919431cb6d48f451ca5c31b62ded3273a0
